steps:
  - label: ":package: Ruby dependencies"
    command: |
        source ~/.zshrc
        gem install xcpretty

  - label: ":hammer: Unit Tests"
    command: |
        source ~/.zshrc
        cd Xcode
        xcodebuild \
                -configuration Debug \
                -scheme SwifteriOS \
                -sdk iphonesimulator \
                -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' \
                clean build test | xcpretty --color --report junit